### ISSUE TITLE
Problem in startListening 

### ISSUE THREAD

**Issue by ahmagdy** [EddyVerbruggen/nativescript-speech-recognition#4]
Hi
when i'm using the code like this
```
this.speechRecognition.startListening({
            locale: "en-US",
            onResult: (transcription: SpeechRecognitionTranscription) => {
                console.log(JSON.stringify(transcription));
                console.log(`User Finihed?: ${transcription.finished}`);
            },

        }
```
transcription doesn't have a  text property when i'm printing it 
`JS: {"finished":true}
`
so after looking around i found the problem in node_modules in speech-recognition.android.js 
`options.onResult({
                         text: transcripts[0],`
i replaced it with 
`text: transcripts.get(0) `
and it works just find

**Comment by EddyVerbruggen** [comment]
You're right, and that has been reported as #1 and fixed by #2. I'll push it to npm tomorrow!

**Comment by ahmagdy** [comment]
Great Thank you

**Comment by EddyVerbruggen** [comment]
Looks like I pushed 1.1.1 5 days ago, so if you're on that version this problem should not pop up..

**Comment by ahmagdy** [comment]
no 
it still pop up, i tried to remove and install it again, and still the same.
maybe you need to check npm package.

**Comment by EddyVerbruggen** [comment]
I think you're right. The problem is that PR adjusted the .ts file (as it should), but publishing to npm didn't update the associated .js version. Let me see..

**Comment by EddyVerbruggen** [comment]
1.1.1 is dead, long live 1.1.2!
